### PR TITLE
Changed splash foreground color

### PR DESCRIPTION
**Pull request by Mailaender**
My intention is to make the black font white (easier to read on dark grey splash). Not sure if `startupForegroundColor="FFFFFF"` is the right thing.

### CODE REVIEW

**Comment by Mailaender** [comment]
Guess we need to fix the build at https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.vogella.vde.luna/ to test.

**Comment by Mailaender** [comment]
Nope, startupForegroundColor is not the text color.

**Comment by vogella** [comment]
I think this needs to be done via CSS. Can you open an Eclipse bug asking
that the startup screen should have CSS ids for its elements so that it can
be styled? This is also a great thing for you to fix

2014-03-16 11:03 GMT+01:00 Matthias Mailänder notifications@github.com:

**Comment by Mailaender** [comment]
I don't understand why this does not work https://github.com/eclipse/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/splash/EclipseSplashHandler.java#L96

**Comment by vogella** [comment]
I think it is overridden by the CSS engine.

2014-03-29 12:21 GMT+01:00 Matthias Mailänder notifications@github.com:

**Comment by Mailaender** [comment]
This seems to work for vanilla Eclipse Luna which uses a light grey on the splash screen.

**Comment by Mailaender** [comment]
Do I need to prepare a patch similiar to https://bugs.eclipse.org/bugs/show_bug.cgi?id=430848 or does https://git.eclipse.org/c/platform/eclipse.platform.ui.git/commit/?id=29bb58b693e30bc43d9847eb42a2a82182d34ba1 already fix this issue?

**Comment by vogella** [comment]
It does fix it in the platform. Theere is still one follow up fix needed:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=419377

But for voclipse there is nothing to do, as we use use the default code +
dark CSS.

#fixed

2014-04-03 9:17 GMT+02:00 Matthias Mailänder notifications@github.com:

**Comment by Mailaender** [comment]
I see that you also tried to verify by retriggering releng.aggregator. Looks like it needs maintenance:

```
[WARNING] The requested profile "update-branding-plugins" could not be activated because it does not exist.
```

**Pull request merged**
