### PR TITLE
Remove the SpringSource update site

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of https://github.com/vogellacompany/com.vogella.vde/pull/96 to fix the build.

### CODE REVIEW

**Comment by vogella** [comment]
I think we also need to remove the spring feature from the product

**Comment by Mailaender** [comment]
Can't find it. Already gone?

**Comment by vogella** [comment]
Maybe. Lets try....

**Comment by Mailaender** [comment]
Looking good so far. Except maybe that download.eclipse.org keeps redirecting to really slow mirrors in mainland China which is known for their exceptionally bad connection to the rest of the world.

**Comment by Mailaender** [comment]
Worked. Updating https://build.vogella.com/ci/view/voclipse/job/C-MASTER-com.voclipse.packaging/ now.

**Comment by vogella** [comment]
Super! Thanks
Am 16.05.2014 13:34 schrieb "Matthias Mailänder" notifications@github.com:

**Pull request merged**
